# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-18 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=255)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='presence',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presences.Room'),
        ),
        migrations.AlterUniqueTogether(
            name='presence',
            unique_together=set([('room', 'channel_name')]),
        ),
    ]
